#!/bin/bash

if [ $# -lt 1 ]; then
    echo "usage: poissemble <reads fasta> [celera options]"
    exit
fi

# first, convert fasta file to fastq with blank qual
java -jar ~/GitHub/poisson/scripts/convertFastaAndQualToFastq.jar $1 > $1.fastq
# next, call celera with custom spec file, passing through rest of arguments
PBcR -length 500 -l assembly -s ~/GitHub/poisson/scripts/oxford.spec -fastq $1.fastq  "${@:2}"
