#!/bin/bash

if [ $# -lt 1 ]; then
    echo "usage: poissemble [reads fasta]"
    exit
fi

java -jar convertFastaAndQualToFastq.jar $1 > $1.fastq
PBcR -length 500 -l assembly -s oxford.spec -fastq $1.fastq  genomeSize=48500
