#!/bin/bash

if [ $# -lt 3 ]; then
    echo "usage: poissalign <ref fasta> <src fasta> <output bam>"
    exit
fi

# index the ref fasta file
samtools faidx $1
# build a database of it, same name
lastdb $1 $1
# align the fasta file to it
#lastal -s 2 -T 0 -Q 0 -a 1 -b 1 -r 1 -q 1 $1 $2 | last-map-probs -m 0.4 | maf-convert sam | samtools view -t $1.fai -S -b - | samtools sort - $3
lastal -s 2 -T 0 -Q 0 -a 1 -b 1 -r 1 -q 1 $1 $2 | maf-convert sam | samtools view -t $1.fai -S -b - | samtools sort - $3
samtools index $3.bam

rm -f $1.bck $1.des $1.prj $1.sds $1.ssp $1.suf $1.tis
